# -*- coding: utf-8 -*-
"""
Single source of truth for the documentary.

This module defines the FULL original narration, broken into chapters and
spoken "cues". Everything else in the project is generated from this file:

  * the neural-TTS narration scratch track (build_audio.py)
  * the synced video timeline   (build_audio.py -> timeline.json)
  * the human-readable script    (build_audio.py -> docs/SCRIPT.md)
  * the burned-in / sidecar subtitles (.srt)

Conventions used inside cue text:
  *word*   -> emphasized keyword (highlighted in captions, kept in speech)
  " ... "  -> dramatic pause (rendered as a beat of silence)

The story is ORIGINAL and motivational. It is intentionally NON-political and
focuses on ambition, resilience, risk, failure and the comeback mindset.
"""

# Per-chapter cinematic colour themes (used by the video backdrops).
THEMES = {
    "cold_open": {"a": "#05070d", "b": "#0b1424", "accent": "#e7b15a"},
    "title":     {"a": "#04060c", "b": "#12203b", "accent": "#f0c674"},
    "roots":     {"a": "#0a0c12", "b": "#241a12", "accent": "#d9a05b"},
    "discipline":{"a": "#070b14", "b": "#13233f", "accent": "#7fb2ff"},
    "learn":     {"a": "#0b0a0f", "b": "#2a2030", "accent": "#caa6ff"},
    "build":     {"a": "#060810", "b": "#0e2a33", "accent": "#4fd3c4"},
    "fame":       {"a": "#0a0810", "b": "#33203a", "accent": "#ff8fd1"},
    "fall":      {"a": "#0c0708", "b": "#3a1414", "accent": "#ff6b6b"},
    "comeback":  {"a": "#070c0a", "b": "#123524", "accent": "#5ef0a0"},
    "global":    {"a": "#05080f", "b": "#10233f", "accent": "#5ea8ff"},
    "leadership":{"a": "#0a0a0c", "b": "#2c2a18", "accent": "#f0d264"},
    "mindset":   {"a": "#08090f", "b": "#1c2444", "accent": "#9fb6ff"},
    "success":   {"a": "#0b0906", "b": "#33260f", "accent": "#f2b85a"},
    "finale":    {"a": "#04060b", "b": "#1a2c4d", "accent": "#ffd884"},
}

# scene: a visual "mode" the Remotion backdrop will switch on.
#   options: skyline | stars | grid | timeline | map | flare | dark
CHAPTERS = [
    {
        "key": "cold_open", "num": 0, "kind": "hook",
        "title": "", "kicker": "", "scene": "flare",
        "cues": [
            {"t": "Love him ... or hate him.", "pause": 0.6},
            {"t": "One fact remains *undeniable*.", "pause": 0.5},
            {"t": "Donald Trump became one of the most *recognized* names on Earth.", "pause": 0.6},
            {"t": "But the story behind that name ... is not the one you think.", "pause": 0.6},
            {"t": "It is a story of *risk*.", "pause": 0.35},
            {"t": "Of *failure*.", "pause": 0.35},
            {"t": "Of public humiliation.", "pause": 0.45},
            {"t": "And of a *comeback* almost nobody believed was possible.", "pause": 0.6},
            {"t": "The world counted him out ... more than once.", "pause": 0.5},
            {"t": "This is not about politics.", "pause": 0.4},
            {"t": "This is about *ambition*. And what it truly costs ... to never quit.", "pause": 0.8},
        ],
    },
    {
        "key": "title", "num": 0, "kind": "title",
        "title": "THE ART OF NEVER QUITTING", "kicker": "a study in ambition, resilience, and the cost of a dream",
        "scene": "stars",
        "cues": [
            {"t": "Every empire begins long before the world is watching.", "pause": 0.6},
            {"t": "This is the story of how a single, stubborn idea ... refused to die.", "pause": 0.7},
        ],
    },
    {
        "key": "roots", "num": 1, "kind": "chapter",
        "title": "ROOTS", "kicker": "Childhood & Family", "scene": "skyline",
        "cues": [
            {"t": "In the borough of Queens, New York, a boy grew up in the shadow of a father who built his fortune one brick at a time.", "pause": 0.5},
            {"t": "Fred Trump was not a gentle teacher. He was *relentless*.", "pause": 0.45},
            {"t": "He measured a man by what he *produced* ... not by what he promised.", "pause": 0.5},
            {"t": "He woke before dawn, walked the buildings himself, and missed nothing.", "pause": 0.5},
            {"t": "Excellence was not a word in that house. It was a *habit*.", "pause": 0.55},
            {"t": "Around that family dinner table, there were no participation trophies. There were only *results*.", "pause": 0.55},
            {"t": "And so the boy learned three lessons early.", "pause": 0.4},
            {"t": "Be a winner. Never show weakness. And never ... *ever* ... quit.", "pause": 0.6},
            {"t": "But beneath that hard exterior, something else was forming. A *hunger*.", "pause": 0.5},
            {"t": "A boy who looked across the river at the glittering towers of Manhattan ... and refused to believe they were out of reach.", "pause": 0.55},
            {"t": "While other children dreamed small, he was already dreaming in *skyscrapers*.", "pause": 0.5},
            {"t": "Money was never really the lesson. The lesson was *standards*.", "pause": 0.5},
            {"t": "And standards, once they live inside you ... never leave.", "pause": 0.55},
            {"t": "The question was simple. Would that hunger build him ... or destroy him?", "pause": 0.7},
        ],
    },
    {
        "key": "discipline", "num": 2, "kind": "chapter",
        "title": "THE FORGE", "kicker": "Education & Early Ambition", "scene": "grid",
        "cues": [
            {"t": "By his teenage years, that energy had nowhere to go. He was bold, restless, *impossible* to contain.", "pause": 0.5},
            {"t": "So his father made a decision that would change everything. He sent him away ... to a military academy.", "pause": 0.55},
            {"t": "For a boy used to getting his way, it was a shock.", "pause": 0.4},
            {"t": "Cold mornings. Strict discipline. Officers who did not care about his last name.", "pause": 0.5},
            {"t": "Make your bed. Shine your shoes. Stand tall. Small things ... done *perfectly*.", "pause": 0.55},
            {"t": "He hated it. And then ... slowly ... he began to *need* it.", "pause": 0.6},
            {"t": "And here is the part most people miss. He did not break. He *adapted*.", "pause": 0.55},
            {"t": "He learned that discipline was not the enemy of ambition. It was the *engine* of it.", "pause": 0.55},
            {"t": "He rose through the ranks ... earning respect not given, but *taken* through effort.", "pause": 0.5},
            {"t": "Then came the University of Pennsylvania, and its prestigious Wharton School of business.", "pause": 0.5},
            {"t": "He was not there to blend in. He was there to learn the one game he intended to *dominate*.", "pause": 0.55},
            {"t": "And he was already certain ... he would win it.", "pause": 0.7},
        ],
    },
    {
        "key": "learn", "num": 3, "kind": "chapter",
        "title": "THE APPRENTICE", "kicker": "Learning the Game", "scene": "grid",
        "cues": [
            {"t": "After graduation, most young men would have chased *comfort*. He chased *pressure*.", "pause": 0.5},
            {"t": "He went straight into his father's business ... collecting rents in the outer boroughs, learning the unglamorous truth of real estate.", "pause": 0.55},
            {"t": "He saw how deals were really made. Not in fantasies ... but in numbers, leverage, and *nerve*.", "pause": 0.55},
            {"t": "He studied the city like a chessboard. Which blocks were dying. Which were about to wake up.", "pause": 0.55},
            {"t": "Everyone else saw buildings. He saw *moves*.", "pause": 0.5},
            {"t": "But the outer boroughs could never hold him. His eyes were fixed across the water ... on Manhattan.", "pause": 0.5},
            {"t": "The most expensive, most competitive, most ruthless real estate market on the planet.", "pause": 0.5},
            {"t": "His father warned him. That world was a different league. Bigger players. Bigger risks.", "pause": 0.5},
            {"t": "Bigger ways ... to lose *everything*.", "pause": 0.55},
            {"t": "Donald heard the warning.", "pause": 0.4},
            {"t": "And then he did the one thing that would define his entire life. He *ignored* it.", "pause": 0.7},
        ],
    },
    {
        "key": "build", "num": 4, "kind": "chapter",
        "title": "THE RISE", "kicker": "Building the Empire", "scene": "skyline",
        "cues": [
            {"t": "Manhattan in the nineteen-seventies was a city on its knees.", "pause": 0.45},
            {"t": "Crime was high. Investors were fleeing. Entire blocks sat abandoned.", "pause": 0.5},
            {"t": "Everyone saw a dying city. He saw the *opportunity* of a lifetime.", "pause": 0.55},
            {"t": "While others ran ... he made his move.", "pause": 0.5},
            {"t": "A crumbling hotel beside Grand Central Station. Nobody wanted it. He saw a *landmark*.", "pause": 0.55},
            {"t": "Through relentless negotiation, bold tax deals, and sheer audacity, he transformed it into a gleaming tower of glass.", "pause": 0.55},
            {"t": "It was his proof of concept. And it was only the *beginning*.", "pause": 0.5},
            {"t": "Critics laughed. They said an outer-borough kid had no business playing on Fifth Avenue.", "pause": 0.5},
            {"t": "He let them laugh. Then he handed them a *skyline*.", "pause": 0.6},
            {"t": "Then came the building that would put his name on the skyline ... and into the language itself.", "pause": 0.55},
            {"t": "A tower of glass and brass, rising on Fifth Avenue.", "pause": 0.5},
            {"t": "He did not just build it. He *marketed* it.", "pause": 0.5},
            {"t": "He understood something his rivals did not. He was not selling square footage. He was selling a *feeling*.", "pause": 0.55},
            {"t": "Success ... you could move into.", "pause": 0.55},
            {"t": "Each project was bigger than the last. Each risk ... heavier than the one before.", "pause": 0.55},
            {"t": "The name on the door was becoming a *promise*. And the world was starting to listen.", "pause": 0.7},
        ],
    },
    {
        "key": "fame", "num": 5, "kind": "chapter",
        "title": "THE ICON", "kicker": "A National Figure", "scene": "flare",
        "cues": [
            {"t": "By the nineteen-eighties, he was no longer just a developer. He was a *character*.", "pause": 0.5},
            {"t": "A symbol of an entire decade's obsession with success.", "pause": 0.5},
            {"t": "His face filled magazine covers. His deals became headlines.", "pause": 0.5},
            {"t": "He published a book about the art of the deal ... that turned a businessman into a household name.", "pause": 0.55},
            {"t": "Casinos. An airline. A yacht the size of a small town.", "pause": 0.5},
            {"t": "He was not just building properties. He was building a *legend* ... in real time, in front of an entire country.", "pause": 0.6},
            {"t": "The kid from Queens now owned a piece of the skyline he once stared at from across the river.", "pause": 0.55},
            {"t": "He had learned a secret most builders never grasp. Attention itself ... is a kind of *currency*.", "pause": 0.6},
            {"t": "And he was about to spend all of it ... on the biggest bet of his life.", "pause": 0.6},
            {"t": "But here is the law that never changes.", "pause": 0.45},
            {"t": "The higher you climb ... the farther you can *fall*.", "pause": 0.5},
            {"t": "And the fall ... was coming.", "pause": 0.8},
        ],
    },
    {
        "key": "fall", "num": 6, "kind": "chapter",
        "title": "THE FALL", "kicker": "Crisis & Setback", "scene": "dark",
        "cues": [
            {"t": "At the dawn of the nineteen-nineties, the music stopped.", "pause": 0.5},
            {"t": "The economy collapsed. Real estate values cratered.", "pause": 0.5},
            {"t": "And the empire built on bold borrowing ... suddenly faced a brutal reckoning.", "pause": 0.55},
            {"t": "The numbers were staggering. *Billions* of dollars in debt.", "pause": 0.5},
            {"t": "He had borrowed against a future that suddenly vanished overnight.", "pause": 0.5},
            {"t": "Personal guarantees. The kind where, if the deal dies ... it takes *you* with it.", "pause": 0.6},
            {"t": "Casinos bleeding money. Banks circling.", "pause": 0.45},
            {"t": "The newspapers that once crowned him ... now sharpened their knives.", "pause": 0.55},
            {"t": "Finished. Washed up. The end of an era.", "pause": 0.5},
            {"t": "The same world that built him up ... now lined up to watch him *fall*.", "pause": 0.6},
            {"t": "The phone that once never stopped ringing ... went silent.", "pause": 0.6},
            {"t": "By his own admission, there were nights he walked past beggars on the street ... and quietly understood they were worth more than he was.", "pause": 0.6},
            {"t": "He was billions ... in the red.", "pause": 0.55},
            {"t": "This is the moment the story was supposed to end. The cautionary tale.", "pause": 0.55},
            {"t": "But failure is not the end of the story.", "pause": 0.5},
            {"t": "Sometimes ... it is the *beginning* of the real one.", "pause": 0.8},
        ],
    },
    {
        "key": "comeback", "num": 7, "kind": "chapter",
        "title": "THE COMEBACK", "kicker": "Resilience Under Fire", "scene": "stars",
        "cues": [
            {"t": "Here is what separates the forgotten ... from the *legendary*.", "pause": 0.5},
            {"t": "It is not whether you fall. *Everyone* falls.", "pause": 0.5},
            {"t": "It is what you do ... while you are down.", "pause": 0.55},
            {"t": "Cornered by debt, he did not panic. He *negotiated*.", "pause": 0.5},
            {"t": "He walked into rooms full of bankers who could have ended him ... and changed the entire conversation.", "pause": 0.55},
            {"t": "His logic was ice cold. He owed so much that destroying him would destroy them too.", "pause": 0.55},
            {"t": "So instead of his enemy ... the debt became his *leverage*.", "pause": 0.55},
            {"t": "He stopped asking why this happened ... and started asking ... what now.", "pause": 0.6},
            {"t": "That single shift ... from victim to *architect* ... changed everything.", "pause": 0.6},
            {"t": "Slowly, deal by deal, he clawed his way back from the edge.", "pause": 0.5},
            {"t": "He restructured. He survived. He held on ... when every rational person said let go.", "pause": 0.6},
            {"t": "And when the dust finally settled ... the man they had buried in the headlines was still *standing*.", "pause": 0.55},
            {"t": "Bruised. Humbled. But *unbroken*.", "pause": 0.55},
            {"t": "He had learned the most expensive lesson money can buy.", "pause": 0.5},
            {"t": "That a name ... and a refusal to quit ... can be worth more than any building.", "pause": 0.8},
        ],
    },
    {
        "key": "global", "num": 8, "kind": "chapter",
        "title": "THE BRAND", "kicker": "Going Global", "scene": "map",
        "cues": [
            {"t": "The comeback taught him a new kind of power.", "pause": 0.45},
            {"t": "He realized he no longer had to *own* everything. He could simply lend his *name* to it.", "pause": 0.55},
            {"t": "The name became the product.", "pause": 0.45},
            {"t": "Towers across the globe, from New York to Dubai, would rise with his name in gold ... often built by others, but carrying his promise.", "pause": 0.6},
            {"t": "Then came television.", "pause": 0.45},
            {"t": "A show that placed him at the center of a corporate empire ... delivering a single, unforgettable phrase to millions of homes each week.", "pause": 0.6},
            {"t": "Suddenly he was not just a name in the financial press. He was a *global icon* ... recognized on every continent on Earth.", "pause": 0.6},
            {"t": "The boy from Queens had turned three letters of his last name into one of the most valuable brands in the world.", "pause": 0.55},
            {"t": "And he had done it *twice*.", "pause": 0.45},
            {"t": "He had found the most valuable real estate of all. The space inside people's *minds*.", "pause": 0.6},
            {"t": "And you cannot foreclose ... on a reputation.", "pause": 0.6},
            {"t": "Once with concrete. And once ... with sheer *will*.", "pause": 0.8},
        ],
    },
    {
        "key": "leadership", "num": 9, "kind": "chapter",
        "title": "THE PLAYBOOK", "kicker": "Leadership Lessons", "scene": "grid",
        "cues": [
            {"t": "Strip away the noise, the controversy, the headlines ... and you are left with a case study in raw *ambition*.", "pause": 0.55},
            {"t": "So what can we actually learn?", "pause": 0.5},
            {"t": "First ... *confidence*. He understood that the world often takes you at the value you place on yourself.", "pause": 0.55},
            {"t": "He never undersold.", "pause": 0.45},
            {"t": "Second ... *persistence*. He treated every no not as a wall ... but as a door he simply had not found the handle to yet.", "pause": 0.6},
            {"t": "Third ... *risk*. He understood that comfort and greatness rarely live on the same street.", "pause": 0.55},
            {"t": "To win big ... he was willing to lose big.", "pause": 0.5},
            {"t": "And fourth ... *adaptability*. When concrete stopped paying, he sold his name. When print faded, he conquered television.", "pause": 0.6},
            {"t": "He never married himself to a single method. He married himself to the *goal*.", "pause": 0.6},
            {"t": "And beneath them all hides a quieter lesson. *Decisiveness*.", "pause": 0.5},
            {"t": "While others gathered one more opinion ... he had already *moved*.", "pause": 0.8},
        ],
    },
    {
        "key": "mindset", "num": 10, "kind": "chapter",
        "title": "THE MIND", "kicker": "Mindset Lessons", "scene": "stars",
        "cues": [
            {"t": "But tactics are nothing without the mind behind them.", "pause": 0.45},
            {"t": "The real architecture was never steel and glass. It was *mindset*.", "pause": 0.55},
            {"t": "He thought in skyscrapers while others thought in single floors.", "pause": 0.5},
            {"t": "Most people shrink their dreams to fit their fears. He did the *opposite*.", "pause": 0.55},
            {"t": "He grew ... until the fear itself ... looked small.", "pause": 0.6},
            {"t": "Because here is a strange truth. It takes the same energy to dream small ... as it does to dream big.", "pause": 0.6},
            {"t": "So why ... dream small?", "pause": 0.55},
            {"t": "He treated criticism as a tax you pay for being *relevant*.", "pause": 0.5},
            {"t": "The louder the doubters ... the closer he believed he was to something that mattered.", "pause": 0.55},
            {"t": "And failure? He refused to let it define him.", "pause": 0.5},
            {"t": "To him, failure was *tuition*. Painful, expensive ... but never wasted, as long as you walked out having learned.", "pause": 0.6},
            {"t": "This mindset is available to anyone. It costs nothing. And it changes *everything*.", "pause": 0.8},
        ],
    },
    {
        "key": "success", "num": 11, "kind": "chapter",
        "title": "THE PRICE", "kicker": "What Success Requires", "scene": "grid",
        "cues": [
            {"t": "So let us be honest about what success really demands.", "pause": 0.5},
            {"t": "Because it is not luck. And it is rarely fair.", "pause": 0.5},
            {"t": "And there is no version of this story where you skip the hard part.", "pause": 0.55},
            {"t": "It demands *discipline*. The boring, unglamorous repetition of showing up when no one is clapping.", "pause": 0.6},
            {"t": "It demands *consistency*. A single bold move means nothing.", "pause": 0.5},
            {"t": "A thousand of them, stacked over decades ... build an empire.", "pause": 0.55},
            {"t": "It demands *long-term thinking*. The willingness to plant trees whose shade you may never sit in.", "pause": 0.6},
            {"t": "And above all ... it demands *personal responsibility*.", "pause": 0.5},
            {"t": "The refusal to blame the economy, the critics, or the odds. The decision to own your outcome ... completely.", "pause": 0.6},
            {"t": "The struggle is not in the way of the path. The struggle ... *is* the path.", "pause": 0.6},
            {"t": "Self-belief is not arrogance.", "pause": 0.45},
            {"t": "It is simply the first investor willing to bet on you ... before anyone else will.", "pause": 0.8},
        ],
    },
    {
        "key": "finale", "num": 12, "kind": "finale",
        "title": "THE CLIMB", "kicker": "Final Motivation", "scene": "skyline",
        "cues": [
            {"t": "So here we are ... at the end of the climb.", "pause": 0.5},
            {"t": "And the lesson was never really about real estate, or fame, or one man's name in gold.", "pause": 0.6},
            {"t": "It was about what happens inside a human being ... when the world says stop ... and something deeper says *keep going*.", "pause": 0.7},
            {"t": "Remember the man billions in debt, walking past those beggars in the night.", "pause": 0.55},
            {"t": "By every measure, he was finished. The story should have ended there.", "pause": 0.6},
            {"t": "But it didn't.", "pause": 0.6},
            {"t": "Because success is not about *avoiding* failure.", "pause": 0.5},
            {"t": "Success is about *surviving* it.", "pause": 0.6},
            {"t": "The people who achieve the extraordinary are almost never the most talented in the room.", "pause": 0.55},
            {"t": "They are simply the ones who refused to quit ... when everyone expected them to.", "pause": 0.7},
            {"t": "Whether in business, in leadership, or in the quiet battles of your own life ...", "pause": 0.5},
            {"t": "persistence remains one of the most powerful forces on Earth.", "pause": 0.6},
            {"t": "Your name may never appear on a tower. But the principles are the same.", "pause": 0.6},
            {"t": "Look closely at every name we admire ... and you will find the same fingerprint.", "pause": 0.55},
            {"t": "They were knocked down ... and they *chose* to rise.", "pause": 0.6},
            {"t": "That choice is not reserved for the famous. It is offered to *everyone*. Including you.", "pause": 0.65},
            {"t": "Think bigger than your fear. Stay standing when you are knocked down. And never ... *ever* ... quit.", "pause": 0.7},
            {"t": "The climb ... is yours now.", "pause": 1.0},
        ],
    },
    {
        "key": "finale", "num": 12, "kind": "endcard",
        "title": "THINK BIGGER. STAY RESILIENT. NEVER QUIT.", "kicker": "", "scene": "stars",
        "cues": [],  # silent end card with music swell
    },
]
